### ISSUE TITLE
Wrong API endpoint for search

### ISSUE THREAD

**Issue by AndriusBartulis** [icons8/api-docs#1]
The API docs suggest that the API endpoint is https://**api**.icons8.com/api/iconsets/v4/search, however that does not seem to work. After some experimentation I found https://**search**.icons8.com/api/iconsets/v4/search to work.

Should the docs be changed to reflect this? Or am I missing something?

**Comment by sergeychekmenev** [comment]
Hi Andrius! That's right, the correct link for the end point would be: https://search.icons8.com/api/iconsets/v4/search However the doc does not contain the wrong link that you are mentioning: https://api.icons8.com/api/iconsets/v4/search. So actually there is nothing to change/fix. Actually, the doc by itself has to be updated with more technical details on regard to the integration.

**Comment by sergeychekmenev** [comment]
and by the way, Andrius, where did you find this wrong endpoint?

**Comment by AndriusBartulis** [comment]
@sergeychekmenev I followed the link on icons8.com footer, to the API docs. Then in the v4 Search api section, you can see the wrong endpoint being shown in the code example on the right side of the page.

https://icons8.docs.apiary.io/#reference/0/search/by-keyword-v4

![image](https://user-images.githubusercontent.com/6200977/48142812-69f5d580-e2a5-11e8-9280-38eb9053768f.png)

**Comment by sergeychekmenev** [comment]
Hi Andrius, thank you man for this very detailed answer. We do value and appreciate your help. I've already asked my colleagues to update the doc. Thank you for your interest to the Icons8!
